name       : haskell-rio
version    : 0.1.2.0
release    : 1
source     :
    - http://hackage.haskell.org/package/rio-0.1.2.0/rio-0.1.2.0.tar.gz : 98333b9376ce9cdc77ebe84b35a5fbb41ef846cc00efc12970bca1c19f948910
license    : MIT
component  : programming.haskell
summary    : A standard library for Haskell
description: |
    A standard library for Haskell
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions
    - haskell-microlens
    - haskell-mtl
    - haskell-primitive
    - haskell-typed-process
    - haskell-unliftio
    - haskell-unordered-containers
    - haskell-vector
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
