name       : haskell-rio
version    : 0.1.19.0
release    : 2
source     :
    - https://hackage.haskell.org/package/rio-0.1.19.0/rio-0.1.19.0.tar.gz : 55e77225e481d9be41f883bcabf5c716fb1e80511428f5e391d7a0cf73bc7b12
license    : MIT
component  : programming.haskell
summary    : A standard library for Haskell
description: |
    A standard library for Haskell
builddeps  :
    - haskell-cabal-install
    - haskell-exceptions-devel
    - haskell-microlens-mtl-devel
    - haskell-typed-process-devel
    - haskell-unliftio-devel
    - haskell-unordered-containers-devel
    - haskell-vector-devel
rundeps    :
    - devel :
        - haskell-exceptions-devel
        - haskell-microlens-mtl-devel
        - haskell-typed-process-devel
        - haskell-unliftio-devel
        - haskell-unordered-containers-devel
        - haskell-vector-devel
networking : yes
setup      : |
    %cabal_configure --dynlibdir="\$libdir/\$compiler/\$pkgid"
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
